name: "Sync GitHub stars with Raindrop"

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run sync script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Your personal access token with read:user
          RAINDROP_TOKEN: ${{ secrets.RAINDROP_TOKEN }}
          RAINDROP_COLLECTION_ID: ${{ secrets.RAINDROP_COLLECTION_ID }}
        run: node src/script.js
